services:
  dev:
    image: "observatorio/ui-registro-femicidios"
    user: "${UID}:${GID}"
    build:
      context: .
      target: development
    command: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_API_AQSNV_SERVER=http://localhost:8080
      - VITE_API_AQSNV_CLIENT_ID=1234
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src/
      - ./public:/app/public/
      - ./index.html:/app/index.html
      - ./.eslintrc.cjs:/app/.eslintrc.cjs
      - ./vite.config.ts:/app/vite.config.ts
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
