export default {
    victim: {
        fullName: "",
        age: "",
        gender: "",
        nationality: "",
        isSexualWorker: "unknown",
        isMissingPerson: "unknown",
        isNativePeople: "unknown",
        isPregnant: "unknown",
        hasDisabillity: "unknown",
        occupation: "",
        hasChildren: "unknown",
    },
    aggressor: {
        fullName: "",
        age: "",
        gender: "",
        hasLegalComplaintHistory: "unknown",
        hasPreviousCases: "unknown",
        wasInPrison: "unknown",
        behaviourPostCase: "unknown",
    },

    occurredAt: "",
    momentOfDay: "",
    province: "",
    location: "",
    geographicLocation: "",
    place: "",
    murderWeapon: "",
    wasJudicialized: "unknown",
    hadLegalComplaints: "unknown",
    isRape: "unknown",
    isRelatedToOrganizedCrime: "unknown",
    organizedCrimeNotes: "",
    generalNotes: "",
    newsLinks: "",
};
