import dayjs from "dayjs";

export default {
    victim: {
        fullName: "",
        age: "",
        gender: "",
        nationality: "",
        isSexualWorker: false,
        isMissingPerson: false,
        isNativePeople: false,
        isPregnant: false,
        hasDisabillity: false,
        occupation: "",
        hasChildren: "unknown",
    },
    aggressor: {
        fullName: "",
        age: "",
        gender: "",
        hasLegalComplaintHistory: false,
        hasPreviousCases: false,
        wasInPrison: false,
        behaviourPostCase: false,
    },

    occurredAt: dayjs(),
    momentOfDay: "",
    province: "",
    location: "",
    geographicLocation: "",
    place: "",
    murderWeapon: "",
    wasJudicialized: false,
    hadLegalComplaints: false,
    isRape: false,
    isRelatedToOrganizedCrime: false,
    organizedCrimeNotes: "",
    generalNotes: "",
    newsLinks: "",
};
