/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the current user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            pictureUrl: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refreshes the feeds by connecting to our feed sources */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the full list of feed items */
        get: {
            parameters: {
                query?: {
                    /** @description Filter results to only contain feed items in the given status */
                    status?: "backlog" | "inProgress" | "done";
                    /** @description Maximum amount of results to return */
                    limit?: number;
                    /** @description Cursor as returned on the `next` property of a previous request to this endpoint */
                    start?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed/items/{feedItemId}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assigns a given feed item to the current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Feed item to update */
                    feedItemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Removes the assigned user for a given feed item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Feed item to update */
                    feedItemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed/items/{feedItemId}/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marks a single feed item that is assigned to the current user as done */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Feed item to update */
                    feedItemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Marks a single feed item that is assigned to the current user as in progress */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Feed item to update */
                    feedItemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed/items/{feedItemId}/irrelevant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a single feed item as irrelevant and assign to current user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Feed item to update */
                    feedItemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Removes the flag irrelevant for a given feed item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Feed item to update */
                    feedItemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all cases */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of cases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            victimName?: string;
                            province?: string;
                            location?: string;
                            aggressor?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a new case */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        caseCategory: components["schemas"]["CaseCategory"];
                        wasItAnAttempt?: boolean;
                        isInsufficientDataOrUnderInvestigation?: boolean;
                        /** Format: date */
                        occurredAt: string;
                        momentOfDay?: components["schemas"]["CaseMomentOfDay"];
                        province: components["schemas"]["Province"];
                        location: string;
                        geographicLocation?: components["schemas"]["CaseGeographicLocation"];
                        place: components["schemas"]["CasePlace"];
                        murderWeapon?: components["schemas"]["CaseMurderWeapon"];
                        hadLegalComplaints?: boolean;
                        totalLegalComplaints?: number;
                        wasJudicialized?: boolean;
                        judicialMeasures?: components["schemas"]["CaseJudicialMeasure"][];
                        victimBondAggressor?: components["schemas"]["CaseVictimBondAggressor"];
                        isRape?: boolean;
                        isRelatedToOrganizedCrime?: boolean;
                        organizedCrimeNotes?: string;
                        generalNotes?: string;
                        newsLinks: string[];
                        victim: {
                            fullName?: string;
                            age?: number;
                            gender?: components["schemas"]["Gender"];
                            nationality?: components["schemas"]["Nationality"];
                            isSexualWorker?: boolean;
                            isMissingPerson?: boolean;
                            isNativePeople?: boolean;
                            isPregnant?: boolean;
                            hasDisabillity?: boolean;
                            occupation?: string;
                            hasChildren?: boolean;
                            numberOfChildren?: number;
                        };
                        aggressor: {
                            fullName?: string;
                            age?: number;
                            gender?: components["schemas"]["Gender"];
                            hasLegalComplaintHistory?: boolean;
                            hasPreviousCases?: boolean;
                            wasInPrison?: boolean;
                            behaviourPostCase?: components["schemas"]["CaseAggressorBehaviorPostCase"];
                            belongsSecurityForce?: boolean;
                            securityForce?: components["schemas"]["CaseAggressorSecurityForce"];
                        };
                    };
                };
            };
            responses: {
                /** @description Case created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["ValidationErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        Gender: "MUJER" | "HOMBRE" | "NO_BINARIO" | "TRANS" | "TRAVESTI";
        /** @enum {unknown} */
        Province: "BUENOS_AIRES" | "CATAMARCA" | "CHACO" | "CHUBUT" | "CABA" | "CORDOBA" | "CORRIENTES" | "ENTRE_RIOS" | "FORMOSA" | "JUJUY" | "LA_PAMPA" | "LA_RIOJA" | "MENDOZA" | "MISIONES" | "NEUQUEN" | "RIO_NEGRO" | "SALTA" | "SAN_JUAN" | "SAN_LUIS" | "SANTA_CRUZ" | "SANTA_FE" | "SANTIAGO_DEL_ESTERO" | "TIERRA_DEL_FUEGO" | "TUCUMAN";
        /** @enum {unknown} */
        Nationality: "ARGENTINA" | "BOLIVIA" | "BRASIL" | "COLOMBIA" | "CHILE" | "ECUADOR" | "GUYANA" | "PARAGUAY" | "PERU" | "SURINAM" | "URUGUAY" | "VENEZUELA" | "GUYANA_FRANCESA" | "OTRA";
        /** @enum {unknown} */
        CaseCategory: "FEMICIDIO_DIRECTO" | "FEMICIDIO_VINCULADO" | "TRAVESTICIDIO_TRANSFEMICIDIO_LESBICIDIO" | "INSTIGACION_AL_SUICIDIO" | "CRIMEN_DE_ODIO";
        /** @enum {unknown} */
        CaseMomentOfDay: "DIURNO" | "NOCTURNO";
        /** @enum {unknown} */
        CaseGeographicLocation: "URBANA" | "RURAL";
        /** @enum {unknown} */
        CasePlace: "VIVIENDA_DE_LA_VICTIMA" | "VIVIENDA_DEL_AGRESOR" | "VIA_PUBLICA" | "VIVIENDA_DE_ALGUN_FAMILIAR" | "VIVIENDA_DE_AMBAS_PARTES_CONVIVIAN" | "OTRO_LUGAR";
        /** @enum {unknown} */
        CaseMurderWeapon: "A_GOLPES" | "AHOGADA" | "ARMA_BLANCA" | "ARMA_DE_FUEGO" | "ARROJADA_POR_EL_BALCON" | "ASFIXIA" | "ATROPELLADA" | "DESCUARTIZADA" | "EMPALAMIENTO" | "EMPUJO_POR_LAS_ESCALERAS" | "QUEMADA_CALCINADA" | "OTRA_FORMA";
        /** @enum {unknown} */
        CaseJudicialMeasure: "ALIMENTOS_PROVISIONALES" | "ASISTENCIA_PSICOLOGICA" | "BOTON_ANTIPANICO" | "COMPENSACION_ECONOMICA" | "CUSTODIA_PERSONAL" | "MONITOREO_ELECTRONICO_DEL_AGRESOR" | "PROHIBICION_DE_ACERCAMIENTO" | "PROHIBICION_DE_CONTACTO" | "PROHIBICION_DE_DISPONER_DE_BIENES" | "PROVISION_DE_UN_LUGAR_SEGURO" | "REINGRESO_DE_LA_VICTIMA" | "RESTITUCION_DE_PERTENENCIAS" | "SALIDA_DEL_HOGAR" | "SUSPENSION_DEL_REGIMEN_DE_VISITAS" | "OTRA";
        /** @enum {unknown} */
        CaseVictimBondAggressor: "PAREJA_ACTUAL" | "EX_PAREJA" | "FAMILIAR_MADRE" | "FAMILIAR_HIJA" | "FAMILIAR_HIJO" | "FAMILIAR_HERMANA" | "FAMILIAR_HERMANO" | "FAMILIAR_NIETA" | "FAMILIAR_NIETO" | "FAMILIAR_SOBRINA" | "FAMILIAR_SOBRINO" | "FAMILIAR_SUEGRA" | "FAMILIAR_SUEGRO" | "FAMILIAR_BISNIETO" | "FAMILIAR_CUÑADO" | "FAMILIAR_CUÑADA" | "FAMILIAR_PADRE" | "CONOCIDO_NO_FAMILIAR" | "DESCONOCIDO";
        /** @enum {unknown} */
        CaseAggressorBehaviorPostCase: "SE_SUICIDO" | "INTENTO_SUICIDARSE" | "OCULTO_SU_AUTORIA" | "SE_FUGO" | "INTENTO_ESCAPARSE" | "SE_ENTREGO_CONFESO" | "SE_DESHIZO_DEL_CUERPO" | "PIDIO_AYUDA_ASISTIO_A_LA_VICTIMA" | "SE_RESISTIO_A_LA_AUTORIDAD" | "NINGUNA_DE_LAS_ANTERIORES";
        /** @enum {unknown} */
        CaseAggressorSecurityForce: "POLICIA" | "EX_POLICIA_O_POLICIA_RETIRADO" | "EX_FUNCIONARIO_DEL_SERVICIO_PENITENCIARIO" | "FUNCIONARIO_DEL_SERVICIO_PENITENCIARIO" | "GENDARME" | "MILITAR" | "GUARDIA_URBANA_MUNICIPAL" | "SOLDADO_VOLUNTARIO" | "PREFECTURA_NAVAL_ARGENTINA" | "OTRA FUERZA";
    };
    responses: {
        /** @description Bad request */
        ValidationErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "parameter" | "body";
                    path: string;
                    message: string;
                }[];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
