/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as OauthCbRouteImport } from './routes/oauth.cb'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases/index'
import { Route as AuthenticatedCasesNewRouteImport } from './routes/_authenticated/cases/new'
import { Route as AuthenticatedCasesCaseIdEditRouteImport } from './routes/_authenticated/cases/$caseId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OauthCbRoute = OauthCbRouteImport.update({
  id: '/oauth/cb',
  path: '/oauth/cb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasesNewRoute = AuthenticatedCasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasesCaseIdEditRoute =
  AuthenticatedCasesCaseIdEditRouteImport.update({
    id: '/cases/$caseId/edit',
    path: '/cases/$caseId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/oauth/cb': typeof OauthCbRoute
  '/cases/new': typeof AuthenticatedCasesNewRoute
  '/cases/': typeof AuthenticatedCasesIndexRoute
  '/cases/$caseId/edit': typeof AuthenticatedCasesCaseIdEditRoute
}
export interface FileRoutesByTo {
  '/oauth/cb': typeof OauthCbRoute
  '/': typeof AuthenticatedIndexRoute
  '/cases/new': typeof AuthenticatedCasesNewRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/cases/$caseId/edit': typeof AuthenticatedCasesCaseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/oauth/cb': typeof OauthCbRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cases/new': typeof AuthenticatedCasesNewRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/_authenticated/cases/$caseId/edit': typeof AuthenticatedCasesCaseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/oauth/cb' | '/cases/new' | '/cases/' | '/cases/$caseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/oauth/cb' | '/' | '/cases/new' | '/cases' | '/cases/$caseId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/oauth/cb'
    | '/_authenticated/'
    | '/_authenticated/cases/new'
    | '/_authenticated/cases/'
    | '/_authenticated/cases/$caseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OauthCbRoute: typeof OauthCbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/oauth/cb': {
      id: '/oauth/cb'
      path: '/oauth/cb'
      fullPath: '/oauth/cb'
      preLoaderRoute: typeof OauthCbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cases/new': {
      id: '/_authenticated/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AuthenticatedCasesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cases/$caseId/edit': {
      id: '/_authenticated/cases/$caseId/edit'
      path: '/cases/$caseId/edit'
      fullPath: '/cases/$caseId/edit'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCasesNewRoute: typeof AuthenticatedCasesNewRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
  AuthenticatedCasesCaseIdEditRoute: typeof AuthenticatedCasesCaseIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCasesNewRoute: AuthenticatedCasesNewRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
  AuthenticatedCasesCaseIdEditRoute: AuthenticatedCasesCaseIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OauthCbRoute: OauthCbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
